### ISSUE TITLE
stream_options für Gateways ergänzen

### ISSUE THREAD

**Issue by tinokramm** [terminal42/contao-notification_center#190]
Hallo.

Wir haben Probleme beim Mailversand via TLS über einen sehr restriktiven Mailserver. Der Versand über Contao funktioniert nur, wenn stream_options in der config.yml definiert werden. Es fehlt im NC die Möglichkeit diese stream_options für zusätzliche Gateways zu speichern. Ohne die zusätzlichen Optionen schlägt der Versand mit der Meldung „Unable to connect with TLS encryption“ fehl.

```
swiftmailer:
    mailers:
        default:
            transport: smtp
            host: hostname
            username: username
            password: password
            port: 587
            encryption: tls
            stream_options:
                ssl:
                    verify_peer: false
                    verify_peer_name: false
                    allow_self_signed: true
```

Man kann natürlich auch folgenden „Patch“ für den Swiftmailer verwenden, aber der geht nach jedem Update verloren …

https://github.com/swiftmailer/swiftmailer/issues/544#issuecomment-218408969

Danke für Hilfe

Tino

**Comment by tinokramm** [comment]
Wie kann ich prüfen, ob der SMTP-Server tatsächlich ein invalides SSL-Zertifikat verwendet?

**Comment by aschempp** [comment]
das kann ich dir leider nicht wirklich beantworten. Aber die Konfiguration sagt ja genau das
```yaml
ssl: # => SSL-Einestellungen
    verify_peer: false # => Remote-Zertifikat nicht validieren
    verify_peer_name: false # => Name im Zertifikat nicht prüfen
    allow_self_signed: true # => Lokal ausgestellte Zertifikate (ohne Trusted Remote) zulassen
```
